# Generated by Django 3.2.8 on 2021-10-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='function',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('region', models.CharField(choices=[('N', 'North'), ('E', 'East'), ('W', 'West'), ('S', 'South')], default=None, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sub_location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('fk_location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.location')),
            ],
        ),
        migrations.CreateModel(
            name='sub_function',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('fk_function', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.function')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='fk_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.state'),
        ),
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('fk_function', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.function')),
                ('fk_sub_function', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.sub_function')),
            ],
        ),
    ]
