# Generated by Django 3.2.8 on 2021-11-09 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_location',
            name='fk_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.state'),
        ),
        migrations.CreateModel(
            name='user_group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(null=True)),
                ('phone', models.CharField(max_length=10)),
                ('adhaar', models.CharField(max_length=12)),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(null=True)),
                ('phone', models.CharField(max_length=10)),
                ('adhaar', models.CharField(max_length=12)),
                ('doj', models.DateField(null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('fk_designation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.designation')),
                ('fk_function', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.function')),
                ('fk_location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.location')),
                ('fk_state', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.state')),
                ('fk_sub_function', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.sub_function')),
                ('fk_sub_location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.sub_location')),
                ('obspoc', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obspoc', to='onboarding.user_group')),
                ('recruiter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to='onboarding.user_group')),
            ],
        ),
    ]
