# Generated by Django 3.2.8 on 2021-11-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_auto_20211113_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='obspoc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.user_group'),
        ),
    ]
